// ─────────────────────────────────────────────────────────────
//  companies.js  —  Default companies list
//  Tum JSON tab se aur add kar sakte ho
// ─────────────────────────────────────────────────────────────

var DEFAULT_COMPANIES = [
  // ── PRODUCT ──
  { name: "Google India",         email: "jobs@google.com",               type: "product"  },
  { name: "Microsoft India",      email: "careers@microsoft.com",         type: "product"  },
  { name: "Amazon India",         email: "amazon-india-jobs@amazon.com",  type: "product"  },
  { name: "Adobe India",          email: "careers@adobe.com",             type: "product"  },
  { name: "Atlassian India",      email: "careers@atlassian.com",         type: "product"  },
  { name: "Salesforce India",     email: "india.careers@salesforce.com",  type: "product"  },
  { name: "Uber India",           email: "india-careers@uber.com",        type: "product"  },
  { name: "Myntra",               email: "careers@myntra.com",            type: "product"  },
  { name: "Flipkart",             email: "careers@flipkart.com",          type: "product"  },
  { name: "Meesho",               email: "hiring@meesho.com",             type: "product"  },
  // ── STARTUP ──
  { name: "PolicyBazaar",         email: "careers@policybazaar.com",      type: "startup"  },
  { name: "PaisaBazaar",          email: "hr@paisabazaar.com",            type: "startup"  },
  { name: "Dream11",              email: "careers@dream11.com",           type: "startup"  },
  { name: "Cars24",               email: "careers@cars24.com",            type: "startup"  },
  { name: "Delhivery",            email: "careers@delhivery.com",         type: "startup"  },
  { name: "OfBusiness",           email: "hr@ofbusiness.in",              type: "startup"  },
  { name: "BrowserStack",         email: "careers@browserstack.com",      type: "startup"  },
  { name: "Spinny",               email: "careers@spinny.com",            type: "startup"  },
  { name: "Lenskart",             email: "careers@lenskart.com",          type: "startup"  },
  { name: "Nykaa",                email: "careers@nykaa.com",             type: "startup"  },
  { name: "Groww",                email: "careers@groww.in",              type: "startup"  },
  { name: "Zerodha",              email: "careers@zerodha.com",           type: "startup"  },
  { name: "Razorpay",             email: "careers@razorpay.com",          type: "startup"  },
  { name: "PhonePe",              email: "careers@phonepe.com",           type: "startup"  },
  { name: "Zomato",               email: "careers@zomato.com",            type: "startup"  },
  { name: "Swiggy",               email: "careers@swiggy.in",             type: "startup"  },
  { name: "CRED",                 email: "careers@cred.club",             type: "startup"  },
  { name: "Zepto",                email: "careers@zepto.co",              type: "startup"  },
  { name: "Jupiter Money",        email: "careers@jupiter.money",         type: "startup"  },
  { name: "Cashfree Payments",    email: "careers@cashfree.com",          type: "startup"  },
  { name: "CleverTap",            email: "careers@clevertap.com",         type: "startup"  },
  { name: "Postman",              email: "careers@postman.com",           type: "startup"  },
  { name: "Darwinbox",            email: "careers@darwinbox.com",         type: "startup"  },
  { name: "Hevo Data",            email: "careers@hevodata.com",          type: "startup"  },
  { name: "Sprinklr India",       email: "careers@sprinklr.com",          type: "startup"  },
  { name: "PhysicsWallah",        email: "careers@pw.live",               type: "startup"  },
  { name: "upGrad",               email: "careers@upgrad.com",            type: "startup"  },
  { name: "Unacademy",            email: "careers@unacademy.com",         type: "startup"  },
  { name: "Chargebee",            email: "careers@chargebee.com",         type: "startup"  },
  { name: "Juspay",               email: "careers@juspay.in",             type: "startup"  },
  { name: "MakeMyTrip",           email: "careers@makemytrip.com",        type: "startup"  },
  { name: "Slice Fintech",        email: "careers@sliceit.com",           type: "startup"  },
  // ── SERVICES ──
  { name: "Publicis Sapient",     email: "careers@publicissapient.com",   type: "services" },
  { name: "GlobalLogic",          email: "careers@globallogic.com",       type: "services" },
  { name: "ThoughtWorks India",   email: "careers@thoughtworks.com",      type: "services" },
  { name: "Accenture India",      email: "india.careers@accenture.com",   type: "services" },
  { name: "IBM India",            email: "ibm_india_jobs@in.ibm.com",     type: "services" },
  { name: "Nagarro",              email: "careers@nagarro.com",           type: "services" },
  { name: "Newgen Software",      email: "hr@newgensoft.com",             type: "services" },
  { name: "Tata Elxsi",           email: "careers@tataelxsi.com",         type: "services" },
  { name: "Coforge",              email: "careers@coforge.com",           type: "services" },
  { name: "Zensar Technologies",  email: "careers@zensar.com",            type: "services" },
];
